### ISSUE TITLE
Issue with Preflight Over Redirect in LLM Servers

### ISSUE THREAD

**Issue by 0x4139** [manimohans/obsidian-local-llm-helper#3]
#### Description

The issue occurs in most LLM servers (Groq, Fireworks, OpenAI Azure, etc.) because preflight over redirect is not supported. This leads to compatibility issues when connecting to these servers.

#### Recommendation

To address this, I recommend updating the documentation and the code to support the protocol (either `http` or `https`) directly in the server address. Additionally, it would be beneficial to remove the port specification as it seems redundant and contributes to compatibility issues.

#### Reference

For reference, the relevant code section can be found [here](https://github.com/manimohans/obsidian-local-llm-helper/blob/da7dacfef67f2c6869291f070d2b732e4d9de140/main.ts#L523).

I am more than happy to send over a pull request if you're interested

**Comment by manimohans** [comment]
v1.1.3 should address this.
